baseURL = "https://minami-hair.com/"
languageCode = "ja-jp"
title = "ヘアーサロンみなみ"
hasCJKLanguage = true
pluralizeListTitles = false
enableGitInfo = true
copyright = "© 2023 ヘアーサロンみなみ<br>Powered by Hugo"
googleAnalytics = ""

[pagination]
pagerSize = 12

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
date= ["publishDate", ":filename", "date", ":fileModTime"]
publishDate= ["publishDate", ":filename", "date", ":fileModTime"]
lastmod = [":git", "lastmod", "date", "publishDate"]
expiryDate = ["expiryDate"]

[params]
secondTitle = " | 髪を理めてきたヘアサロン"
blogTitle = "ブログ"
contact = "minami.hairsalon@gmail.com"
description = "<ruby>髪<rp>（</rp><rt>かみ</rt><rp>）</rp></ruby>を<ruby>理<rp>（</rp><rt>おさ</rt><rp>）</rp></ruby>めてきた<br><span>ヘアサロン</span>"
blogDescription = "ヘアーサロンみなみのブログ"
dateFormat = "2006.01.02"
googleAdsense = ""

[params.sns]
line = ""
Instagram =""

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
categories = "/blog/categories/:title"
tags = "/blog/tags/:title"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

[[related.indices]]
  name = "categories"
  weight = 80

[[related.indices]]
  name = "tags"
  weight = 60

[[related.indices]]
  name = "date"
  weight = 10

[menu]
[[menu.main]]
    name = "店舗情報"
    pre = ""
    weight = -150
    url = "/#about"
[[menu.main]]
    name = "メニュー＆料金"
    pre = ""
    weight = -130
    url = "/menu/"
[[menu.main]]
    name = "ご予約・お問い合わせ"
    pre = ""
    weight = -120
    url = "/contact/"
[[menu.main]]
    name = "BLOG"
    pre = ""
    weight = -110
    url = "/blog/"

[[menu.footer]]
    name = "ホーム"
    pre = ""
    weight = -50
    url = "/"
[[menu.footer]]
    name = "サイトポリシー"
    pre = ""
    weight = -40
    url = "/policy/"
[[menu.footer]]
    name = "プライバシーポリシー"
    pre = ""
    weight = -30
    url = "/privacy/"
[[menu.footer]]
    name = "お問い合わせ"
    pre = ""
    weight = -20
    url = "https://forms.gle/oCcJf8Qc8TvW4r939"
 
[outputs]
home = [ "HTML", "RSS"]
